/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Cat extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5754773959307028009L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Cat\",\"namespace\":\"avro\",\"fields\":[{\"name\":\"catId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"animal\",\"type\":{\"type\":\"record\",\"name\":\"Animal\",\"fields\":[{\"name\":\"animalId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"age\",\"type\":\"int\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Cat> ENCODER =
      new BinaryMessageEncoder<Cat>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Cat> DECODER =
      new BinaryMessageDecoder<Cat>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Cat> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Cat> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Cat> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Cat>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Cat to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Cat from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Cat instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Cat fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String catId;
  @Deprecated public avro.Animal animal;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Cat() {}

  /**
   * All-args constructor.
   * @param catId The new value for catId
   * @param animal The new value for animal
   */
  public Cat(java.lang.String catId, avro.Animal animal) {
    this.catId = catId;
    this.animal = animal;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return catId;
    case 1: return animal;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: catId = value$ != null ? value$.toString() : null; break;
    case 1: animal = (avro.Animal)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'catId' field.
   * @return The value of the 'catId' field.
   */
  public java.lang.String getCatId() {
    return catId;
  }


  /**
   * Sets the value of the 'catId' field.
   * @param value the value to set.
   */
  public void setCatId(java.lang.String value) {
    this.catId = value;
  }

  /**
   * Gets the value of the 'animal' field.
   * @return The value of the 'animal' field.
   */
  public avro.Animal getAnimal() {
    return animal;
  }


  /**
   * Sets the value of the 'animal' field.
   * @param value the value to set.
   */
  public void setAnimal(avro.Animal value) {
    this.animal = value;
  }

  /**
   * Creates a new Cat RecordBuilder.
   * @return A new Cat RecordBuilder
   */
  public static avro.Cat.Builder newBuilder() {
    return new avro.Cat.Builder();
  }

  /**
   * Creates a new Cat RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Cat RecordBuilder
   */
  public static avro.Cat.Builder newBuilder(avro.Cat.Builder other) {
    if (other == null) {
      return new avro.Cat.Builder();
    } else {
      return new avro.Cat.Builder(other);
    }
  }

  /**
   * Creates a new Cat RecordBuilder by copying an existing Cat instance.
   * @param other The existing instance to copy.
   * @return A new Cat RecordBuilder
   */
  public static avro.Cat.Builder newBuilder(avro.Cat other) {
    if (other == null) {
      return new avro.Cat.Builder();
    } else {
      return new avro.Cat.Builder(other);
    }
  }

  /**
   * RecordBuilder for Cat instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Cat>
    implements org.apache.avro.data.RecordBuilder<Cat> {

    private java.lang.String catId;
    private avro.Animal animal;
    private avro.Animal.Builder animalBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.Cat.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.catId)) {
        this.catId = data().deepCopy(fields()[0].schema(), other.catId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.animal)) {
        this.animal = data().deepCopy(fields()[1].schema(), other.animal);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasAnimalBuilder()) {
        this.animalBuilder = avro.Animal.newBuilder(other.getAnimalBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing Cat instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.Cat other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.catId)) {
        this.catId = data().deepCopy(fields()[0].schema(), other.catId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.animal)) {
        this.animal = data().deepCopy(fields()[1].schema(), other.animal);
        fieldSetFlags()[1] = true;
      }
      this.animalBuilder = null;
    }

    /**
      * Gets the value of the 'catId' field.
      * @return The value.
      */
    public java.lang.String getCatId() {
      return catId;
    }


    /**
      * Sets the value of the 'catId' field.
      * @param value The value of 'catId'.
      * @return This builder.
      */
    public avro.Cat.Builder setCatId(java.lang.String value) {
      validate(fields()[0], value);
      this.catId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'catId' field has been set.
      * @return True if the 'catId' field has been set, false otherwise.
      */
    public boolean hasCatId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'catId' field.
      * @return This builder.
      */
    public avro.Cat.Builder clearCatId() {
      catId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'animal' field.
      * @return The value.
      */
    public avro.Animal getAnimal() {
      return animal;
    }


    /**
      * Sets the value of the 'animal' field.
      * @param value The value of 'animal'.
      * @return This builder.
      */
    public avro.Cat.Builder setAnimal(avro.Animal value) {
      validate(fields()[1], value);
      this.animalBuilder = null;
      this.animal = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'animal' field has been set.
      * @return True if the 'animal' field has been set, false otherwise.
      */
    public boolean hasAnimal() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'animal' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public avro.Animal.Builder getAnimalBuilder() {
      if (animalBuilder == null) {
        if (hasAnimal()) {
          setAnimalBuilder(avro.Animal.newBuilder(animal));
        } else {
          setAnimalBuilder(avro.Animal.newBuilder());
        }
      }
      return animalBuilder;
    }

    /**
     * Sets the Builder instance for the 'animal' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public avro.Cat.Builder setAnimalBuilder(avro.Animal.Builder value) {
      clearAnimal();
      animalBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'animal' field has an active Builder instance
     * @return True if the 'animal' field has an active Builder instance
     */
    public boolean hasAnimalBuilder() {
      return animalBuilder != null;
    }

    /**
      * Clears the value of the 'animal' field.
      * @return This builder.
      */
    public avro.Cat.Builder clearAnimal() {
      animal = null;
      animalBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Cat build() {
      try {
        Cat record = new Cat();
        record.catId = fieldSetFlags()[0] ? this.catId : (java.lang.String) defaultValue(fields()[0]);
        if (animalBuilder != null) {
          try {
            record.animal = this.animalBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("animal"));
            throw e;
          }
        } else {
          record.animal = fieldSetFlags()[1] ? this.animal : (avro.Animal) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Cat>
    WRITER$ = (org.apache.avro.io.DatumWriter<Cat>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Cat>
    READER$ = (org.apache.avro.io.DatumReader<Cat>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.catId);

    this.animal.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.catId = in.readString();

      if (this.animal == null) {
        this.animal = new avro.Animal();
      }
      this.animal.customDecode(in);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.catId = in.readString();
          break;

        case 1:
          if (this.animal == null) {
            this.animal = new avro.Animal();
          }
          this.animal.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










